name: Release package
on:
  release:
    types:
      - published
jobs:
  release:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org
      - name: Install Dependencies
        run: npm ci
      - name: Get the version
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Patch package.json
        run: >
          jq '.version = env.RELEASE_VERSION' package.json > package.$$.json &&
          mv package.$$.json package.json
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
