name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-node
      - run: npm run build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3.4.2
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}